baseURL = "https://jinyongp.dev/"
languageCode = "en-us"
title = "jinyongp.dev"
theme = "minimal"
googleAnalytics = "G-SH0YPW4E1C"
pluralizelisttitles = false
enableRobotsTXT = true

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[params]
author = "jinyongp"
description = "도전하고 성장하는 개발 블로그"
githubUsername = "jinyongp"
accent = "RoyalBlue"
showBorder = true
backgroundColor = "white"
font = "Raleway"                      # should match the name on Google Fonts!
favicon = "favicon.png"
highlight = true
highlightStyle = "github-dark-dimmed"
css = ["css/custom.css"]

repo = "jinyongp/jinyongp.dev"
repoId = "R_kgDOHJDtcg"
category = "Comments"
categoryId = "DIC_kwDOHJDtcs4CXf7o"
lang = "ko"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
url = "/"
name = "Home"
weight = 1

[[menu.main]]
url = "/blog"
name = "Blog"
weight = 2

[[menu.main]]
url = "/study"
name = "Study"
weight = 3

[[menu.main]]
url = "/projects"
name = "Projects"
weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
url = "mailto:dev.jinyongp@gmail.com"
name = "fa-solid fa-square-envelope"
weight = 1

[[menu.icon]]
url = "https://github.com/jinyongp/"
name = "fa-brands fa-github-square"
weight = 2
