baseURL = "https://jinyongp.github.io/blog/"
languageCode = "en-us"
title = "dev.jinyongp"
theme = "minimal"
disqusShortname = "jinyongp" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "jinyongp"
    description = ""
    githubUsername = "jinyongp"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/learned/"
    name = "TIL"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:dev.jinyongp@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jinyongp/"
    name = "fab fa-github"
    weight = 2
