baseURL = "https://jinyongp.github.io"
languageCode = "en-us"
title = "dev.jinyongp"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "jinyongp"
    description = "도전과 배움 그리고 성장"
    githubUsername = "jinyongp"
    accent = "DarkTurquoise"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    favicon = "favicon.png"
    highlight = true
    highlightStyle = "default"
    css = ["css/custom.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Post"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Project"
    weight = 3

[[menu.main]]
    url = "/learned/"
    name = "TIL"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:dev.jinyongp@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jinyongp/"
    name = "fab fa-github"
    weight = 2
