title = "jinyongp.dev"
baseURL = "https://jinyongp.dev/"
copyright = "Copyright 2023. Jinyong Park. All rights reserved."

defaultContentLanguage = "ko"
hasCJKLanguage = true

googleAnalytics = "G-SH0YPW4E1C"
enableRobotsTXT = true

paginate = 5
paginatePath = "page"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[params]
favicon = "favicon.ico"
description = "Jinyong Park's Personal Dev Blog"

[params.style]
font = "Raleway"      # https://fonts.google.com
accent = "65 105 225" # "R G B"

[params.highlight]
theme = "nord"     # https://highlightjs.org/static/demo
version = "11.8.0" # https://cdnjs.cloudflare.com/ajax/libs/highlight.js/x.y.z

[params.author]
name = "Jinyong Park"
username = "jinyongp"
email = "dev.jinyongp@gmail.com"

[params.giscus]
repo = "jinyongp/jinyongp.dev"
repoId = "R_kgDOHJDtcg"
category = "Comments"
categoryId = "DIC_kwDOHJDtcs4CXf7o"
lang = "ko"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "Learn"
pageRef = "/learn"
weight = 3

[[menu.main]]
name = "Series"
pageRef = "/series"
weight = 4

[[menu.icon]]
url = "mailto:dev.jinyongp@gmail.com"
name = "square-envelope"
weight = 1

[[menu.icon]]
url = "https://velog.io/@jinyongp"
name = "square-velog"
weight = 2

[[menu.icon]]
url = "https://github.com/jinyongp/"
name = "square-github"
weight = 3

[outputs]
home = ['HTML', 'RSS']
page = ['HTML', 'RSS']

[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "feed"
