baseURL = "https://jinyongp.dev/"
defaultContentLanguage = "ko"
hasCJKLanguage = true
title = "jinyongp.dev"
googleAnalytics = "G-SH0YPW4E1C"
enableRobotsTXT = true

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[params]
author = "jinyongp"
favicon = "favicon.png"
font = "Raleway"        # https://fonts.google.com
highlight = "hybrid"    # https://highlightjs.org/static/demo
accent = "65 105 225"   # "R G B"

[params.giscus]
repo = "jinyongp/jinyongp.dev"
repoId = "R_kgDOHJDtcg"
category = "Comments"
categoryId = "DIC_kwDOHJDtcs4CXf7o"
lang = "ko"

[markup]
[markup.highlight]
tabWidth = 2
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "Series"
pageRef = "/series"
weight = 3

[[menu.main]]
name = "Learn"
pageRef = "/learn"
weight = 4

[[menu.icon]]
url = "mailto:dev.jinyongp@gmail.com"
name = "envelope"
weight = 1

[[menu.icon]]
url = "https://github.com/jinyongp/"
name = "github"
weight = 2
