baseURL = "https://jinyongp.dev/"
defaultContentLanguage = "ko"
hasCJKLanguage = true
title = "jinyongp.dev"
# googleAnalytics = "G-SH0YPW4E1C"
pluralizelisttitles = false
enableRobotsTXT = true

[params]
author = "jinyongp"
font = "Raleway"     # fonts.google.com
accent = "RoyalBlue"
